# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{meerpush}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Hall"]
  s.date = %q{2009-12-13}
  s.description = %q{MeerPush - Automated deployment for ASP.net websites. Part of Meerkatalyst.com}
  s.email = %q{ben@benhall.me.uk}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "example/dsl/README",
     "example/dsl/script",
     "example/rakefile",
     "lib/meerpush.rb",
     "lib/meerpush/assemblies/Microsoft.Web.Administration.dll",
     "lib/meerpush/assemblies/meerpush.dll",
     "lib/meerpush/assemblies/meerpush.pdb",
     "lib/meerpush/dsl/deploy.rb",
     "lib/meerpush/dsl/steps.rb",
     "lib/meerpush/rake/website.rb"
  ]
  s.homepage = %q{http://github.com/BenHall/meerpush}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{MeerPush - Automated deployment for ASP.net websites}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

